"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$fill\
$cmd_duration\
$line_break
$character
"""

right_format = """
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
"""
palette = 'catppuccin_mocha'
continuation_prompt = ' '

[directory]
style = "fg:mauve"
format = "[$path]($style)"
truncation_length = 5
truncation_symbol = "…/"

[git_branch]
style = "fg:peach"
format = '[ $branch ]($style)'

[nodejs]
style = "fg:blue"
format = '[$version ]($style)'

[c]
style = "fg:blue"
format = '[$version ]($style)'

[rust]
style = "fg:peach"
format = '[$version ]($style)'

[golang]
style = "fg:blue"
format = '[$version ]($style)'

[php]
style = "fg:mauve"
format = '[$version ]($style)'

[java]
style = "fg:red"
format = '[$version ]($style)'

[kotlin]
style = "fg:mauve"
format = '[$version ]($style)'

[haskell]
style = "fg:mauve"
format = '[$version ]($style)'

[python]
style = "fg:yellow"
format = '[$version (\(#$virtualenv\)) ]($style)'

[docker_context]
style = "fg:sapphire"
format = '[$context ](($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:mauve)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
show_milliseconds = false
format = "[$duration]($style)"
style = "fg:yellow"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
