"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](fg:#9399b2)\
$username\
$os\
[](bg:mauve fg:crust)\
$directory\
[](bg:peach fg:mauve)\
$git_branch\
$git_status\
[](fg:peach)\
$fill\
[](fg:mantle)\
$cmd_duration\
$time\
[─╮](fg:#9399b2)\
$line_break
[╰─](fg:#9399b2)\
$character
"""

right_format = """
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:yellow)
[─╯](fg:#9399b2)
"""
palette = 'catppuccin_mocha'
continuation_prompt = ' '

[os]
disabled = false
style = "bg:crust fg:mauve"
format = "[ $symbol  ]($style)"

[os.symbols]
SUSE = ""
Gentoo = "󰣨"
Fedora = ""
Alpine = ""
Arch = ""
Artix = ""
Void = ""

[username]
show_always = true
style_user = "bg:crust fg:mauve"
style_root = "bg:crust fg:red"
format = '[  $user]($style)'

[directory]
style = "bg:mauve fg:crust"
format = "[  $path ]($style)"
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:peach"
format = '[[ $symbol $branch ](fg:crust bg:peach)]($style)'

[git_status]
style = "bg:peach"
format = '[[($all_status$ahead_behind )](fg:crust bg:peach)]($style)'

[nodejs]
symbol = ""
style = "fg:blue"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:blue"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:peach"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:blue"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:mauve"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = " "
style = "fg:red"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:mauve"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:mauve"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:yellow"
format = '[ $symbol( $version)(\(#$virtualenv\)) ]($style)'

[docker_context]
symbol = ""
style = "fg:sapphire"
format = '[ $symbol( $context) ](($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:mantle fg:yellow"
format = '[  $time ]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[](bold fg:mauve)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:lavender)'
vimcmd_replace_symbol = '[](bold fg:lavender)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[fill]
symbol = ' '
style = 'bold green'

[cmd_duration]
show_milliseconds = false
format = "[ 󰚭 $duration ]($style)"
style = "bg:mantle fg:yellow"
disabled = false
show_notifications = false
min_time_to_notify = 45000

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
